package ardo:orderly;

interface core {

    resource game {
        constructor();

        pieces: func() -> list<u32>;
        is-over: func() -> bool;
        tries: func() -> u32;
        correct-pieces-count: func() -> u32;

        play: func(a: u32, b: u32);
    }

    shuffle: func(length: u32) -> list<u32>;
}

world orderly {
    export core;
}
